import React from 'react';
import { render } from 'react-dom';

// import Autosuggest from 'autosuggest/Autosuggest';
import Autosuggest from '../dist/main.js';
import './index.html';

const datalist = [
  { name: { en_gb: 'Afghanistan' }, id: 'AF' },
  { name: { en_gb: 'Åland Islands' }, id: 'AX' },
  { name: { en_gb: 'Albania' }, id: 'AL' },
  { name: { en_gb: 'Algeria' }, id: 'DZ' },
  { name: { en_gb: 'American Samoa' }, id: 'AS' },
  { name: { en_gb: 'AndorrA' }, id: 'AD' },
  { name: { en_gb: 'Angola' }, id: 'AO' },
  { name: { en_gb: 'Anguilla' }, id: 'AI' },
  { name: { en_gb: 'Antarctica' }, id: 'AQ' },
  { name: { en_gb: 'Antigua and Barbuda' }, id: 'AG' },
  { name: { en_gb: 'Argentina' }, id: 'AR' },
  { name: { en_gb: 'Armenia' }, id: 'AM' },
  { name: { en_gb: 'Aruba' }, id: 'AW' },
  { name: { en_gb: 'Australia' }, id: 'AU' },
  { name: { en_gb: 'Austria' }, id: 'AT' },
  { name: { en_gb: 'Azerbaijan' }, id: 'AZ' },
  { name: { en_gb: 'Bahamas' }, id: 'BS' },
  { name: { en_gb: 'Bahrain' }, id: 'BH' },
  { name: { en_gb: 'Bangladesh' }, id: 'BD' },
  { name: { en_gb: 'Barbados' }, id: 'BB' },
  { name: { en_gb: 'Belarus' }, id: 'BY' },
  { name: { en_gb: 'Belgium' }, id: 'BE' },
  { name: { en_gb: 'Belize' }, id: 'BZ' },
  { name: { en_gb: 'Benin' }, id: 'BJ' },
  { name: { en_gb: 'Bermuda' }, id: 'BM' },
  { name: { en_gb: 'Bhutan' }, id: 'BT' },
  { name: { en_gb: 'Bolivia' }, id: 'BO' },
  { name: { en_gb: 'Bosnia and Herzegovina' }, id: 'BA' },
  { name: { en_gb: 'Botswana' }, id: 'BW' },
  { name: { en_gb: 'Bouvet Island' }, id: 'BV' },
  { name: { en_gb: 'Brazil' }, id: 'BR' },
  { name: { en_gb: 'British Indian Ocean Territory' }, id: 'IO' },
  { name: { en_gb: 'Brunei Darussalam' }, id: 'BN' },
  { name: { en_gb: 'Bulgaria' }, id: 'BG' },
  { name: { en_gb: 'Burkina Faso' }, id: 'BF' },
  { name: { en_gb: 'Burundi' }, id: 'BI' },
  { name: { en_gb: 'Cambodia' }, id: 'KH' },
  { name: { en_gb: 'Cameroon' }, id: 'CM' },
  { name: { en_gb: 'Canada' }, id: 'CA' },
  { name: { en_gb: 'Cape Verde' }, id: 'CV' },
  { name: { en_gb: 'Cayman Islands' }, id: 'KY' },
  { name: { en_gb: 'Central African Republic' }, id: 'CF' },
  { name: { en_gb: 'Chad' }, id: 'TD' },
  { name: { en_gb: 'Chile' }, id: 'CL' },
  { name: { en_gb: 'China' }, id: 'CN' },
  { name: { en_gb: 'Christmas Island' }, id: 'CX' },
  { name: { en_gb: 'Cocos (Keeling) Islands' }, id: 'CC' },
  { name: { en_gb: 'Colombia' }, id: 'CO' },
  { name: { en_gb: 'Comoros' }, id: 'KM' },
  { name: { en_gb: 'Congo' }, id: 'CG' },
  { name: { en_gb: 'Congo, The Democratic Republic of the' }, id: 'CD' },
  { name: { en_gb: 'Cook Islands' }, id: 'CK' },
  { name: { en_gb: 'Costa Rica' }, id: 'CR' },
  { name: { en_gb: 'Cote D\'Ivoire' }, id: 'CI' },
  { name: { en_gb: 'Croatia' }, id: 'HR' },
  { name: { en_gb: 'Cuba' }, id: 'CU' },
  { name: { en_gb: 'Cyprus' }, id: 'CY' },
  { name: { en_gb: 'Czech Republic' }, id: 'CZ' },
  { name: { en_gb: 'Denmark' }, id: 'DK' },
  { name: { en_gb: 'Djibouti' }, id: 'DJ' },
  { name: { en_gb: 'Dominica' }, id: 'DM' },
  { name: { en_gb: 'Dominican Republic' }, id: 'DO' },
  { name: { en_gb: 'Ecuador' }, id: 'EC' },
  { name: { en_gb: 'Egypt' }, id: 'EG' },
  { name: { en_gb: 'El Salvador' }, id: 'SV' },
  { name: { en_gb: 'Equatorial Guinea' }, id: 'GQ' },
  { name: { en_gb: 'Eritrea' }, id: 'ER' },
  { name: { en_gb: 'Estonia' }, id: 'EE' },
  { name: { en_gb: 'Ethiopia' }, id: 'ET' },
  { name: { en_gb: 'Falkland Islands (Malvinas)' }, id: 'FK' },
  { name: { en_gb: 'Faroe Islands' }, id: 'FO' },
  { name: { en_gb: 'Fiji' }, id: 'FJ' },
  { name: { en_gb: 'Finland' }, id: 'FI' },
  { name: { en_gb: 'France' }, id: 'FR' },
  { name: { en_gb: 'French Guiana' }, id: 'GF' },
  { name: { en_gb: 'French Polynesia' }, id: 'PF' },
  { name: { en_gb: 'French Southern Territories' }, id: 'TF' },
  { name: { en_gb: 'Gabon' }, id: 'GA' },
  { name: { en_gb: 'Gambia' }, id: 'GM' },
  { name: { en_gb: 'Georgia' }, id: 'GE' },
  { name: { en_gb: 'Germany' }, id: 'DE' },
  { name: { en_gb: 'Ghana' }, id: 'GH' },
  { name: { en_gb: 'Gibraltar' }, id: 'GI' },
  { name: { en_gb: 'Greece' }, id: 'GR' },
  { name: { en_gb: 'Greenland' }, id: 'GL' },
  { name: { en_gb: 'Grenada' }, id: 'GD' },
  { name: { en_gb: 'Guadeloupe' }, id: 'GP' },
  { name: { en_gb: 'Guam' }, id: 'GU' },
  { name: { en_gb: 'Guatemala' }, id: 'GT' },
  { name: { en_gb: 'Guernsey' }, id: 'GG' },
  { name: { en_gb: 'Guinea' }, id: 'GN' },
  { name: { en_gb: 'Guinea-Bissau' }, id: 'GW' },
  { name: { en_gb: 'Guyana' }, id: 'GY' },
  { name: { en_gb: 'Haiti' }, id: 'HT' },
  { name: { en_gb: 'Heard Island and Mcdonald Islands' }, id: 'HM' },
  { name: { en_gb: 'Holy See (Vatican City State)' }, id: 'VA' },
  { name: { en_gb: 'Honduras' }, id: 'HN' },
  { name: { en_gb: 'Hong Kong' }, id: 'HK' },
  { name: { en_gb: 'Hungary' }, id: 'HU' },
  { name: { en_gb: 'Iceland' }, id: 'IS' },
  { name: { en_gb: 'India' }, id: 'IN' },
  { name: { en_gb: 'Indonesia' }, id: 'ID' },
  { name: { en_gb: 'Iran, Islamic Republic Of' }, id: 'IR' },
  { name: { en_gb: 'Iraq' }, id: 'IQ' },
  { name: { en_gb: 'Ireland' }, id: 'IE' },
  { name: { en_gb: 'Isle of Man' }, id: 'IM' },
  { name: { en_gb: 'Israel' }, id: 'IL' },
  { name: { en_gb: 'Italy' }, id: 'IT' },
  { name: { en_gb: 'Jamaica' }, id: 'JM' },
  { name: { en_gb: 'Japan' }, id: 'JP' },
  { name: { en_gb: 'Jersey' }, id: 'JE' },
  { name: { en_gb: 'Jordan' }, id: 'JO' },
  { name: { en_gb: 'Kazakhstan' }, id: 'KZ' },
  { name: { en_gb: 'Kenya' }, id: 'KE' },
  { name: { en_gb: 'Kiribati' }, id: 'KI' },
  { name: { en_gb: 'Korea, Democratic People\'S Republic of' }, id: 'KP' },
  { name: { en_gb: 'Korea, Republic of' }, id: 'KR' },
  { name: { en_gb: 'Kuwait' }, id: 'KW' },
  { name: { en_gb: 'Kyrgyzstan' }, id: 'KG' },
  { name: { en_gb: 'Lao People\'S Democratic Republic' }, id: 'LA' },
  { name: { en_gb: 'Latvia' }, id: 'LV' },
  { name: { en_gb: 'Lebanon' }, id: 'LB' },
  { name: { en_gb: 'Lesotho' }, id: 'LS' },
  { name: { en_gb: 'Liberia' }, id: 'LR' },
  { name: { en_gb: 'Libyan Arab Jamahiriya' }, id: 'LY' },
  { name: { en_gb: 'Liechtenstein' }, id: 'LI' },
  { name: { en_gb: 'Lithuania' }, id: 'LT' },
  { name: { en_gb: 'Luxembourg' }, id: 'LU' },
  { name: { en_gb: 'Macao' }, id: 'MO' },
  { name: { en_gb: 'Macedonia, The Former Yugoslav Republic of' }, id: 'MK' },
  { name: { en_gb: 'Madagascar' }, id: 'MG' },
  { name: { en_gb: 'Malawi' }, id: 'MW' },
  { name: { en_gb: 'Malaysia' }, id: 'MY' },
  { name: { en_gb: 'Maldives' }, id: 'MV' },
  { name: { en_gb: 'Mali' }, id: 'ML' },
  { name: { en_gb: 'Malta' }, id: 'MT' },
  { name: { en_gb: 'Marshall Islands' }, id: 'MH' },
  { name: { en_gb: 'Martinique' }, id: 'MQ' },
  { name: { en_gb: 'Mauritania' }, id: 'MR' },
  { name: { en_gb: 'Mauritius' }, id: 'MU' },
  { name: { en_gb: 'Mayotte' }, id: 'YT' },
  { name: { en_gb: 'Mexico' }, id: 'MX' },
  { name: { en_gb: 'Micronesia, Federated States of' }, id: 'FM' },
  { name: { en_gb: 'Moldova, Republic of' }, id: 'MD' },
  { name: { en_gb: 'Monaco' }, id: 'MC' },
  { name: { en_gb: 'Mongolia' }, id: 'MN' },
  { name: { en_gb: 'Montserrat' }, id: 'MS' },
  { name: { en_gb: 'Morocco' }, id: 'MA' },
  { name: { en_gb: 'Mozambique' }, id: 'MZ' },
  { name: { en_gb: 'Myanmar' }, id: 'MM' },
  { name: { en_gb: 'Namibia' }, id: 'NA' },
  { name: { en_gb: 'Nauru' }, id: 'NR' },
  { name: { en_gb: 'Nepal' }, id: 'NP' },
  { name: { en_gb: 'Netherlands' }, id: 'NL' },
  { name: { en_gb: 'Netherlands Antilles' }, id: 'AN' },
  { name: { en_gb: 'New Caledonia' }, id: 'NC' },
  { name: { en_gb: 'New Zealand' }, id: 'NZ' },
  { name: { en_gb: 'Nicaragua' }, id: 'NI' },
  { name: { en_gb: 'Niger' }, id: 'NE' },
  { name: { en_gb: 'Nigeria' }, id: 'NG' },
  { name: { en_gb: 'Niue' }, id: 'NU' },
  { name: { en_gb: 'Norfolk Island' }, id: 'NF' },
  { name: { en_gb: 'Northern Mariana Islands' }, id: 'MP' },
  { name: { en_gb: 'Norway' }, id: 'NO' },
  { name: { en_gb: 'Oman' }, id: 'OM' },
  { name: { en_gb: 'Pakistan' }, id: 'PK' },
  { name: { en_gb: 'Palau' }, id: 'PW' },
  { name: { en_gb: 'Palestinian Territory, Occupied' }, id: 'PS' },
  { name: { en_gb: 'Panama' }, id: 'PA' },
  { name: { en_gb: 'Papua New Guinea' }, id: 'PG' },
  { name: { en_gb: 'Paraguay' }, id: 'PY' },
  { name: { en_gb: 'Peru' }, id: 'PE' },
  { name: { en_gb: 'Philippines' }, id: 'PH' },
  { name: { en_gb: 'Pitcairn' }, id: 'PN' },
  { name: { en_gb: 'Poland' }, id: 'PL' },
  { name: { en_gb: 'Portugal' }, id: 'PT' },
  { name: { en_gb: 'Puerto Rico' }, id: 'PR' },
  { name: { en_gb: 'Qatar' }, id: 'QA' },
  { name: { en_gb: 'Reunion' }, id: 'RE' },
  { name: { en_gb: 'Romania' }, id: 'RO' },
  { name: { en_gb: 'Russian Federation' }, id: 'RU' },
  { name: { en_gb: 'RWANDA' }, id: 'RW' },
  { name: { en_gb: 'Saint Helena' }, id: 'SH' },
  { name: { en_gb: 'Saint Kitts and Nevis' }, id: 'KN' },
  { name: { en_gb: 'Saint Lucia' }, id: 'LC' },
  { name: { en_gb: 'Saint Pierre and Miquelon' }, id: 'PM' },
  { name: { en_gb: 'Saint Vincent and the Grenadines' }, id: 'VC' },
  { name: { en_gb: 'Samoa' }, id: 'WS' },
  { name: { en_gb: 'San Marino' }, id: 'SM' },
  { name: { en_gb: 'Sao Tome and Principe' }, id: 'ST' },
  { name: { en_gb: 'Saudi Arabia' }, id: 'SA' },
  { name: { en_gb: 'Senegal' }, id: 'SN' },
  { name: { en_gb: 'Serbia and Montenegro' }, id: 'CS' },
  { name: { en_gb: 'Seychelles' }, id: 'SC' },
  { name: { en_gb: 'Sierra Leone' }, id: 'SL' },
  { name: { en_gb: 'Singapore' }, id: 'SG' },
  { name: { en_gb: 'Slovakia' }, id: 'SK' },
  { name: { en_gb: 'Slovenia' }, id: 'SI' },
  { name: { en_gb: 'Solomon Islands' }, id: 'SB' },
  { name: { en_gb: 'Somalia' }, id: 'SO' },
  { name: { en_gb: 'South Africa' }, id: 'ZA' },
  { name: { en_gb: 'South Georgia and the South Sandwich Islands' }, id: 'GS' },
  { name: { en_gb: 'Spain' }, id: 'ES' },
  { name: { en_gb: 'Sri Lanka' }, id: 'LK' },
  { name: { en_gb: 'Sudan' }, id: 'SD' },
  { name: { en_gb: 'Suriname' }, id: 'SR' },
  { name: { en_gb: 'Svalbard and Jan Mayen' }, id: 'SJ' },
  { name: { en_gb: 'Swaziland' }, id: 'SZ' },
  { name: { en_gb: 'Sweden' }, id: 'SE' },
  { name: { en_gb: 'Switzerland' }, id: 'CH' },
  { name: { en_gb: 'Syrian Arab Republic' }, id: 'SY' },
  { name: { en_gb: 'Taiwan, Province of China' }, id: 'TW' },
  { name: { en_gb: 'Tajikistan' }, id: 'TJ' },
  { name: { en_gb: 'Tanzania, United Republic of' }, id: 'TZ' },
  { name: { en_gb: 'Thailand' }, id: 'TH' },
  { name: { en_gb: 'Timor-Leste' }, id: 'TL' },
  { name: { en_gb: 'Togo' }, id: 'TG' },
  { name: { en_gb: 'Tokelau' }, id: 'TK' },
  { name: { en_gb: 'Tonga' }, id: 'TO' },
  { name: { en_gb: 'Trinidad and Tobago' }, id: 'TT' },
  { name: { en_gb: 'Tunisia' }, id: 'TN' },
  { name: { en_gb: 'Turkey' }, id: 'TR' },
  { name: { en_gb: 'Turkmenistan' }, id: 'TM' },
  { name: { en_gb: 'Turks and Caicos Islands' }, id: 'TC' },
  { name: { en_gb: 'Tuvalu' }, id: 'TV' },
  { name: { en_gb: 'Uganda' }, id: 'UG' },
  { name: { en_gb: 'Ukraine' }, id: 'UA' },
  { name: { en_gb: 'United Arab Emirates' }, id: 'AE' },
  { name: { en_gb: 'United Kingdom' }, id: 'GB' },
  { name: { en_gb: 'United States' }, id: 'US' },
  { name: { en_gb: 'United States Minor Outlying Islands' }, id: 'UM' },
  { name: { en_gb: 'Uruguay' }, id: 'UY' },
  { name: { en_gb: 'Uzbekistan' }, id: 'UZ' },
  { name: { en_gb: 'Vanuatu' }, id: 'VU' },
  { name: { en_gb: 'Venezuela' }, id: 'VE' },
  { name: { en_gb: 'Viet Nam' }, id: 'VN' },
  { name: { en_gb: 'Virgin Islands, British' }, id: 'VG' },
  { name: { en_gb: 'Virgin Islands, U.S.' }, id: 'VI' },
  { name: { en_gb: 'Wallis and Futuna' }, id: 'WF' },
  { name: { en_gb: 'Western Sahara' }, id: 'EH' },
  { name: { en_gb: 'Yemen' }, id: 'YE' },
  { name: { en_gb: 'Zambia' }, id: 'ZM' },
];

const App = () => (
  <div>
    <h2>Autosuggestst</h2>
    <Autosuggest
      datalist={datalist}
      label="name"
      value="id"
      labelKey="en_gb"
    />
  </div>
);

const root = document.getElementById('root');

render(<App />, root);

